export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_DEPARTURE = 'FETCH_DEPARTURE';
export const FETCH_DEPARTURE_SUCCESS = 'FETCH_DEPARTURE_SUCCESS';

export const FETCH_FORECAST = 'FETCH_FORECAST';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';

export const FETCH_FLIGHT = 'FETCH_FLIGHT';
export const FETCH_FLIGHT_SUCCESS = 'FETCH_FLIGHT_SUCCESS';
